### ISSUE TITLE
Runtime import: Can't rotate bones

### ISSUE THREAD

**Issue by EibrielInv** [V-Sekai/godot-vrm#54] opened 2023-01-15 12:30 UTC
When importing a VRM file at runtime and apply a Tween animation to bone rotation, the Tween animation has no effect (no errors).

When using the exact same model imported from the editor the Tween animation affects the model.

Not sure if its really a bug, but I've tried removing the AnimationPlayer and disabling `show_rest_only` on the Skeleton with no effect.

The VRM file I'm using is `AliciaSolid_vrm-0.51.vrm`. And I'm using Tween to allow parametric animation.

What could be the issue?

**Comment by fire** [comment] 2023-01-15 17:51
Can you post a screenshot of the skeleton? 

I want to check if the small axes indicators for rolls are all pointing up or parent to child.

**Comment by EibrielInv** [comment] 2023-01-15 19:26
Hi! I was unable to check the skeleton during runtime. But here is a minimal reproduction scene.

All 4 characters should be facing the same way, since I'm rotating the bones. But the ones imported at runtime remain unchanged. (I'm not using Tween in this case)

![imagen](https://user-images.githubusercontent.com/172656/212562524-d23b9fc9-2329-4345-a3ef-5e7f62c3dd76.png)

[VRMBones.zip](https://github.com/V-Sekai/godot-vrm/files/10421017/VRMBones.zip)

I'm using `v4.0.beta12.official [3c9bf4bc2]`

**Comment by lyuma** [comment] 2023-08-03 20:35
Note: Due to removal of `.vrm_skeleton` property since it uses Godot's new `SkeletonProfileHumanoid` standard, the skeleton will always be accessible using the new unique nodepath `%GeneralSkeleton`.

Here is the current state:
![image](https://github.com/V-Sekai/godot-vrm/assets/39946030/137756eb-8595-42ae-8fdb-9168e8282c50)
To debug, you can right click a VRM root node from the Remote inspector and do "Save Branch as Scene" to .tscn - This has been extraordinarily useful to debug skeleton issues.

In this case, it seems that all bone binds in the mesh Skin are pointing to `&"Root"` which is very unusual. I'll have to take out my debugger and see what's going on,

I'll try and fix this since runtime support is important. Thanks for providing the example project!

**Comment by lyuma** [comment] 2023-08-04 00:18
Thanks for the report. The issue was caused by the fact that you chose to use non-named skin binds, which is a feature that Godot opted to keep support for in 4.x but is rarely used and hence I had never tested.

I have pushed a fix for non-named skin binds in 591d33e

The thing is, while named skin binds are usually used for import due to being enabled by default, the runtime APIs default to flags=0 which does not enable them, so this issue could be hit at runtime.

To test this, you can enable named binds with:
```
	gltf_loader.append_from_file("res://AliciaSolid_vrm-0.51.vrm", gltf_state, EditorSceneFormatImporter.IMPORT_USE_NAMED_SKIN_BINDS)
```

Side note: There is one function related to head hiding, which is a bit slow O(N^2) for non-named skin binds if a model has a large number (hundreds or thousands) of child bones of the head, since it performs a find operation for each bone in the head. I think it's probably fine for real world cases but it's just something I noticed when working on the code.

**Closed by lyuma** 2023-08-04 00:18 UTC
Labels: bug

**Comment by EibrielInv** [comment] 2023-08-04 00:20
Awesome! Thanks for the information 👍🏽
