### ISSUE TITLE
unable to load addon script - Godot 3.4 stable

### ISSUE THREAD

**Issue by benkaranja** [V-Sekai/godot-vrm#27] opened 2021-11-07 22:46 UTC
Hey,

Just encountered error below after upgrading to Godot latest stable.

Error below
--- Debugging process stopped ---
 res://addons/vrm/import_vrm.gd:871 - Parse Error: The function signature doesn't match the parent. Parent signature is: "Node import_scene_from_other_importer(String, int, int, int)".
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/vrm/plugin.gd:7 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR

Thanks

**Comment by lyuma** [comment] 2021-11-07 23:13
Wow!

Looks like a compatibility breakage landed in 3.4 last minute (literally a few days before release) which was needed to fix another compatibility breakage. Nobody saw this coming.

The PR which caused the issue is this one: https://github.com/godotengine/godot/pull/48625

Now, as for why that function signature change causes this issue, I think it's because `import_vrm.gd` attempts to implement two functions with the same name as built-in engine functions:
```gd
func import_animation_from_other_importer(path: String, flags: int, bake_fps: int):
       return self._import_animation(path, flags, bake_fps)


func import_scene_from_other_importer(path: String, flags: int, bake_fps: int):
       return self._import_scene(path, flags, bake_fps)
```
I can't think of any way to fix this without breaking compatibility in some other way.

However, my understanding is the only engine functions you are supposed to override are those starting with `_` - I copied these from some example code actually, and I don't know why the example code needed these two. they aren't called anywhere.

So I might try and fix it by removing these two.

I also need to make a decision about whether to switch 3.4 users back to GDNative which supports runtime import, or to use the new in-engine import API. Maybe I can add some setting for this

**Comment by benkaranja** [comment] 2021-11-08 08:17
I found a workaround by opening the project in a previously compatible Godot (3.2.1), saving and then coming back to Godot 3.4
Dont ask me how it works.

**Comment by fire** [comment] 2021-11-17 05:40
Can confirm.

**Comment by SaracenOne** [comment] 2022-01-03 04:13
We should have an update to 3.4 compatibility branch now if you want to try it. We'll also try see if we can get the assetlib updated today
https://github.com/V-Sekai/godot-vrm/pull/28

**Comment by lyuma** [comment] 2022-01-04 08:32
PR #28 was merged.  Release to AssetLib is pending.

**Closed by lyuma** 2022-01-04 08:32 UTC
